# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}


# ===============================
# DATABASE MYSQL AIVEN
# ===============================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ===============================
# ARCHIVOS
# ===============================
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

app.upload.dir=src/uploads/familias/